export const CLASSROOM_QUERY_KEYS = {
	GET_CLASSROOMS: "GET_CLASSROOMS",
	ENTER_CLASSROOM: "ENTER_CLASSROOM",
	GET_STUDENTS: "GET_STUDENTS",
	LEAVE_CLASSROOM: "LEAVE_CLASSROOM",
	GET_CLASSROOMS_BY_ID: "GET_CLASSROOMS_BY_ID",
}
