import {
	CheckSvg,
	EmailSvg,
	ErrorSvg,
	EyeOffSvg,
	EyeOnSvg,
	LeftSvg,
	UserSvg,
	WarningSvg,
	ChatSvg,
	HomeSvg,
	SunSvg,
	PlusSvg,
	ImageSvg,
	DownSvg,
	UploadSvg,
	CalendarSvg,
	SearchSvg,
	RightSvg,
	CloseSvg,
} from "@/assets/icons"
import { PdfSvg } from "@/assets/icons/PdfSvg"

export const iconMap = {
	calendar: CalendarSvg,
	chat: ChatSvg,
	check: CheckSvg,
	email: EmailSvg,
	error: ErrorSvg,
	eyeOff: EyeOffSvg,
	eyeOn: EyeOnSvg,
	home: HomeSvg,
	image: ImageSvg,
	left: LeftSvg,
	user: UserSvg,
	warning: WarningSvg,
	sun: SunSvg,
	plus: PlusSvg,
	down: DownSvg,
	upload: UploadSvg,
	search: SearchSvg,
	right: RightSvg,
	close: CloseSvg,
	pdf: PdfSvg,
}
